[package]
name = "DooD-encryption-lib"
version = "0.0.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10.3"
hkdf = "0.12.4"
rand = "0.8.5"
serde_json = "1.0.128"
sha2 = "0.10.8"
x25519-dalek = {version= "2.0.1", features= ["reusable_secrets"]}
